Removed old Ruby version dependencies
Origen-SDK/origen_app_generators pull request #11
Opened 2020-11-13 20:27 UTC by info-rchitect

2020-11-13 21:28 UTC, pderouen commented
Looks like the plugin's Gemfile needs update too

2020-11-13 22:14 UTC, ginty commented
I don't think we should remove the byebug gem, just the version constraint

2020-11-13 23:20 UTC, priyavadan commented
Also, Gemfile has an error (end)

Might as well remove ruby 2.2 from the travis config yml file.

2020-11-16 13:19 UTC, info-rchitect commented
> I don't think we should remove the byebug gem, just the version constraint

OK i am fine with that but why would we tie to version 8 vs the latest?

2020-11-16 13:38 UTC, ginty commented
I don't think we should tie to a version, should just list the name without a version in the new Gemfile

2020-11-16 14:06 UTC, ginty requested changes

2020-11-16 14:06 UTC, ginty commented on templates/app_generators/plugin/Gemfile
> +gem 'byebug'
Should not be within this external audience block

2020-11-16 15:32 UTC, priyavadan commented
I want to try out the change to byebug internally on our systems, before this gets merged.

2020-11-24 17:52 UTC, ginty approved these changes
LGTM

2020-12-01 16:29 UTC, priyavadan commented
LGTM!

2020-12-01 16:38 UTC, info-rchitect commented
> LGTM!

Going to merge and then do another PR for moving to github actions

2020-12-01 16:39 UTC, merged